### ISSUE TITLE
Error during compilation on MacOs M1 apple

### ISSUE THREAD

**Issue by ivanv6** [iotaledger/one-click-tangle#31]
Hello, I'm trying to run your one-click code on a Macbook Air M1 with all requirements installed. When I run the `private-tangle.sh script`, It returns this error:

```
Stopping containers...
Generating an initial IOTA address holding all IOTAs...
Creating network "private-tangle" with the default driver
Creating hornet-private-net_address-generator_run ... done
Initial Address generated. You can find the seed at node.seed
Generating a new seed for the coordinator...
Done. Check coordinator.seed
Generating Merkle Tree... of depth 16. This can take time ⏳ ...
sed: 1: "config/config-coo.json": command c expects \ followed by text
```

Could you please check this error? Thanks a lot

**Comment by jmcanterafonseca-iota** [comment]
oh that's an easy fix. You need to install GNU sed on your Mac as follows

https://medium.com/@bramblexu/install-gnu-sed-on-mac-os-and-set-it-as-default-7c17ef1b8f64

then the script should be running ok. Please let us know, thanks!

**Comment by jmcanterafonseca-iota** [comment]
@ivanv6 is it fixed? can we close?

**Comment by jmcanterafonseca-iota** [comment]
closed as it seems to be solved
